"""add user relationship to the contacts

Revision ID: bc1442b1a9c3
Revises: fdf2bb8087dc
Create Date: 2025-03-30 19:45:08.986175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc1442b1a9c3"
down_revision: Union[str, None] = "fdf2bb8087dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("user_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column(
        "contacts", "user_id", server_default=None
    )  # Remove default after applying
    op.create_foreign_key(
        None, "contacts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_column("contacts", "user_id")
    # ### end Alembic commands ###
